botUsername: BobrytsyaBot
botToken: ${TELEGRAM_TOKEN}
newUserMessage: Вас було додано до списку розсилок! Я дам знати, якщо з'явиться інформація про нові відключення електроенергії.
deletedUserMessage: Вас було видалено зі списку розсилки.
wrongCommandResponseMessage: Я не знаю такої команди! Для видалення зі списку розсилки наберіть /delete

accidentsJobTime: 30 0/15 * * * *
outagesJobTime: 0 5 18 * * *

spring:
  datasource:
    url: jdbc:h2:file:./h2/user
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update